development:
  adapter: mysql2
  encoding: utf8
  database: rails-wercker-heroku_development
  username: root
  password: 'password'
  pool: 5
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['WERCKER_MYSQL_DATABASE'] %><%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV['WERCKER_MYSQL_USERNAME'] %>
  password: <%= ENV['WERCKER_MYSQL_PASSWORD'] %>
  host: <%= ENV['WERCKER_MYSQL_HOST'] %>
  port: <%= ENV['WERCKER_MYSQL_PORT'] %>
